#!/usr/bin/env python3
"""Assemble the reviewed OpenAPI fragments; never infer schemas from responses."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FRAGMENTS = ("identity-intake", "commercial-projects", "files-async-reporting", "admin-integration", "guest-intake")
METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}
ERRORS = {
    400: ("BadRequest", "MALFORMED_REQUEST", "The request could not be completed."),
    401: ("Unauthorized", "UNAUTHENTICATED", "Authentication is required."),
    403: ("Forbidden", "FORBIDDEN", "This action is not permitted."),
    404: ("NotFound", "NOT_FOUND", "The resource was not found."),
    405: ("MethodNotAllowed", "METHOD_NOT_ALLOWED", "The request could not be completed."),
    409: ("Conflict", "CONFLICT", "The request could not be completed."),
    412: ("PreconditionFailed", "STALE_VERSION", "The request could not be completed."),
    413: ("PayloadTooLarge", "REQUEST_TOO_LARGE", "The request could not be completed."),
    415: ("UnsupportedMediaType", "UNSUPPORTED_MEDIA_TYPE", "The request could not be completed."),
    422: ("ValidationError", "VALIDATION_FAILED", "The submitted fields are invalid."),
    428: ("PreconditionRequired", "PRECONDITION_REQUIRED", "The request could not be completed."),
    429: ("TooManyRequests", "RATE_LIMITED", "Too many requests. Please retry later."),
    500: ("InternalError", "INTERNAL_ERROR", "An unexpected error occurred."),
    503: ("ServiceUnavailable", "SERVICE_UNAVAILABLE", "The service is temporarily unavailable."),
}


def encoded(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def source_manifest():
    sources = [p for folder in ("app", "routes", "config", "bootstrap", "database/migrations")
               for p in (ROOT / folder).rglob("*.php") if "cache" not in p.parts]
    sources += [ROOT / p for p in ("composer.json", "composer.lock", "docker/nginx/nginx.conf")]
    return {p.relative_to(ROOT).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(sources)}


def build():
    error = {"type": "object", "required": ["error", "request_id"], "additionalProperties": False,
             "properties": {
                 "request_id": {"type": "string", "format": "uuid"},
                 "error": {"type": "object", "required": ["code", "message"], "additionalProperties": False,
                           "properties": {
                               "code": {"type": "string", "enum": [v[1] for v in ERRORS.values()]},
                               "message": {"type": "string"},
                               "fields": {"description": "Only present for validation errors; safe field names and fixed messages.",
                                          "type": "object", "maxProperties": 100,
                                          "propertyNames": {"pattern": "^[a-zA-Z_][a-zA-Z0-9_.]{0,127}$"},
                                          "additionalProperties": {"type": "array", "minItems": 1, "maxItems": 1,
                                                                   "items": {"const": "This field is invalid."}}}}}}}
    params = {}
    for key, name, description in (
        ("Origin", "Origin", "Exact configured HTTPS public origin. Mutations require this or a same-origin Referer. Not a wildcard/subdomain CORS API."),
        ("CsrfToken", "X-XSRF-TOKEN", "For session mutations, URL-decode readable XSRF-TOKEN cookie and echo it here; browser sends the HttpOnly session cookie automatically."),
        ("IfMatch", "If-Match", 'Exact quoted ETag of the operation parent, including quotes. Missing=428, stale/malformed=412; never synthesize from child lock_version.'),
        ("IdempotencyKey", "Idempotency-Key", "16–128 characters from A–Z/a–z/0–9/_.:- (a UUID is a suitable client choice). Retain the same key and payload for an uncertain retry; endpoint-specific precondition, replay and retention checks still apply."),
        ("RequestId", "X-Request-ID", "Optional UUID correlation identifier; otherwise generated by the server. Never send private data in it."),
    ):
        params[key] = {"name": name, "in": "header", "description": description,
                       "required": key in {"IfMatch", "IdempotencyKey", "CsrfToken"}, "schema": {"type": "string"}}
    params["IdempotencyKey"]["schema"].update({"minLength": 16, "maxLength": 128, "pattern": "^[A-Za-z0-9_.:-]{16,128}$"})
    params["RequestId"]["schema"]["format"] = "uuid"
    responses = {}
    for status, (name, code, message) in ERRORS.items():
        example = {"error": {"code": code, "message": message}, "request_id": "019961a0-0000-7000-8000-000000000001"}
        if status == 422:
            example["error"]["fields"] = {"email": ["This field is invalid."]}
        responses[name] = {"description": f"HTTP {status}: {code}. Messages are safe generic text; branch on code, not message.",
                           "headers": {"X-Request-ID": {"schema": {"type": "string", "format": "uuid"}},
                                       "Cache-Control": {"schema": {"type": "string"}}},
                           "content": {"application/json": {"schema": {"$ref": "#/components/schemas/ErrorEnvelope"}, "example": example}}}
        if status in (429, 503):
            responses[name]["headers"]["Retry-After"] = {"description": "Optional integer seconds or HTTP date; not guaranteed on every failure.", "schema": {"type": "string"}}
    spec = {
        "openapi": "3.1.1", "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
        "info": {"title": "HOLOUL frontend API", "version": "1.1.0-g1",
                 "description": "Reviewed B1–B7 baseline plus UNCOMMITTED B8/P1/P2/P3/F1-E1 candidate and additive G1 dual intake. Contract review is not production certification. Production performance certification pending target VPS. Same-origin session API; the only non-/api/v1 frontend operation is Sanctum CSRF initialization."},
        "servers": [{"url": "/", "description": "Same HTTPS origin as the Next.js application"}],
        "paths": {"/api/v1": {"get": {
            "operationId": "apiVersion", "summary": "Read API identity", "tags": ["API"],
            "description": "Public API version marker; readiness and operational health are deliberately excluded.",
            "security": [], "x-personas": ["public"], "x-permissions": [],
            "x-frontend-feature": "API version", "x-source": ["routes/api.php"],
            "responses": {"200": {"description": "API identity", "content": {"application/json": {"schema": {
                "type": "object", "required": ["data"], "additionalProperties": False, "properties": {"data": {
                    "type": "object", "required": ["service", "api_version"], "additionalProperties": False,
                    "properties": {"service": {"const": "HOLOUL"}, "api_version": {"const": "v1"}}}}}}}}}}}},
        "components": {"schemas": {"ErrorEnvelope": error}, "responses": responses, "parameters": params,
                       "securitySchemes": {"SessionCookie": {"type": "apiKey", "in": "cookie", "name": "__Host-holoul_session",
                                                              "description": "HttpOnly; browser-managed with credentials:same-origin. JavaScript must never read this cookie. CSRF proof is separate."}}},
    }
    for name in FRAGMENTS:
        fragment = json.loads((ROOT / f"docs/contracts/{name}.json").read_text())
        for path, operations in fragment["paths"].items():
            dest = spec["paths"].setdefault(path, {})
            assert not (dest.keys() & operations.keys()), f"Duplicate operation: {path}"
            dest.update(operations)
        for kind, entries in fragment.get("components", {}).items():
            dest = spec["components"].setdefault(kind, {})
            assert not (dest.keys() & entries.keys()), f"Duplicate components: {kind}"
            dest.update(entries)
    # Middleware/edge failures apply across routes; domain errors remain explicit.
    for operations in spec["paths"].values():
        for method, operation in operations.items():
            if method not in METHODS:
                continue
            for status in (400, 403, 413, 415, 429, 500, 503):
                operation["responses"].setdefault(str(status), {"$ref": "#/components/responses/" + ERRORS[status][0]})
    spec["paths"] = dict(sorted(spec["paths"].items()))
    return spec


def matrix(spec):
    lines = ["# HOLOUL frontend endpoint matrix", "", "Generated from the reviewed OpenAPI source. Permissions never override ownership, assignment, MFA, recent authentication, visibility or state checks. Empty permission cells mean no named permission, not public access. Health/operational routes are excluded.", "",
             "| Frontend feature | Endpoint | Method | Persona | Permission |", "|---|---|---|---|---|"]
    for path, operations in spec["paths"].items():
        for method, op in operations.items():
            if method in METHODS:
                values = [op["x-frontend-feature"], f"`{path}`", method.upper(), ", ".join(op["x-personas"]), ", ".join(op["x-permissions"]) or "—"]
                lines.append("| " + " | ".join(v.replace("|", "\\|").replace("\n", " ") for v in values) + " |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--freeze-sources", action="store_true", help="Explicitly acknowledge review of implementation changes; never run automatically in CI")
    args = parser.parse_args()
    spec = build()
    outputs = {"docs/openapi.json": encoded(spec), "docs/API-ENDPOINT-MATRIX.md": matrix(spec)}
    if args.freeze_sources:
        outputs["docs/contracts/source-manifest.json"] = encoded(source_manifest())
    for name, contents in outputs.items():
        target = ROOT / name
        if args.check:
            assert target.read_text() == contents, f"Generated contract drift: {name}; review fragments and rebuild"
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            temporary = target.with_suffix(target.suffix + ".tmp")
            temporary.write_text(contents)
            temporary.replace(target)
    if args.check:
        assert json.loads((ROOT / "docs/contracts/source-manifest.json").read_text()) == source_manifest(), "Implementation changed since contract review; inspect schema/authorization changes and explicitly refresh source manifest"
    print(f"OpenAPI assembled: {sum(m in METHODS for p in spec['paths'].values() for m in p)} operations")
