Foreground yes
LocalSocket /run/holoul-clamav/clamd.sock
LocalSocketMode 660
FixStaleSocket yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LogTime no
LogClean no
LogVerbose no
LogFile /dev/null
LogSyslog no
MaxThreads 1
MaxQueue 4
ReadTimeout 20
CommandReadTimeout 5
SendBufTimeout 1000
StreamMaxLength 10M
MaxScanTime 15000
MaxScanSize 40M
MaxFileSize 10M
MaxRecursion 8
MaxFiles 256
MaxEmbeddedPE 10M
MaxHTMLNormalize 10M
MaxHTMLNoTags 10M
MaxScriptNormalize 10M
MaxZipTypeRcg 1M
AlertExceedsMax yes
AlertEncrypted yes
ScanPDF yes
ScanOLE2 yes
ScanArchive yes
SelfCheck 60
ConcurrentDatabaseReload no
