DatabaseDirectory /var/lib/clamav
DatabaseOwner holoul
DatabaseMirror database.clamav.net
Checks 12
ConnectTimeout 10
ReceiveTimeout 60
MaxAttempts 3
TestDatabases yes
ScriptedUpdates yes
Foreground yes
LogTime no
UpdateLogFile /dev/null
